### ISSUE TITLE
Triangulate crashes when rect not provided on init

### ISSUE THREAD

**Issue by dmirauta** [bartekd97/gdDelaunay#2]
Changing [this line](https://github.com/bartekd97/gdDelaunay/blob/cd5391662834507b2e4f0c40c09d51a20fc61f76/addons/gdDelaunay/Delaunay.gd#L209) seems to do the trick, is this intended? This seems to recalc rect when provided and not calc when needed.

**Comment by bartekd97** [comment]
Yes, there was small mistake but in different line. Please check latest commit.
Thanks!

**Comment by dmirauta** [comment]
This now appears to cause division by zero when initialising without providing rect. Is it definitely not the other line? The comment says "calculate rectangle if none" but it only calculates when a rectangle has area and not when it doesn't.

**Comment by bartekd97** [comment]
Right.
It seems to work now thanks to #3
